name: "CI"

on:
  pull_request:
    paths-ignore:
      - "LICENSE"
      - "**.md"
  push:
    branches:
      - "main"
      - "develop"
    paths-ignore:
      - "LICENSE"
      - "**.md"

defaults:
  run:
    shell: "bash"

jobs:
  ci:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Static Check
        run: |
          yarn format:check
          yarn lint
          yarn type-check
          yarn test:ci
