name: "CI"

on:
  pull_request:
    paths-ignore:
      - "LICENSE"
      - "**.md"
  push:
    branches:
      - "main"
      - "develop"
    paths-ignore:
      - "LICENSE"
      - "**.md"

defaults:
  run:
    shell: "bash"

jobs:
  static-check:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Static Check
        run: |
          yarn ci
