name: "deployment"

on:
  push:
    branches:
      - "main"
      - "develop"
    paths:
      - "**.ts"
      - "package.json"
      - "yarn.lock"

jobs:
  deploy-lambda-functions:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
