name: "deployment"

on:
  push:
    branches:
      - "main"
      - "develop"
    paths:
      - "**.ts"
      - "package.json"
      - "yarn.lock"

jobs:
  deploy-lambda-functions:
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        node-version:
          - "14.x"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
